# Use Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Set environment variables to avoid user interaction during installation
ENV DEBIAN_FRONTEND=noninteractive

# Update and install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libopencv-dev \
    # Add any other dependencies required by mapper_from_images
    && rm -rf /var/lib/apt/lists/*

# Clone the mapper_from_images repository
# Replace the URL with the actual repository URL if it's different
RUN git clone https://github.com/SebWiegert/Container.git /code

# Build aruco
RUN cd /code/aruco-3.1.12 && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j4 && \
    make install

# Build mapper_from_images
RUN cd /code/marker_mapper1.0.15 && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j4 && \
    make install

# Set the environment variable to include the library path. otherwise, mapper_from_images won't work
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

# List all files in the folder imgs
RUN ls /imgs
